# Generated by Django 5.1.7 on 2025-04-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'CVT'), ('Dual-Clutch', 'Dual-Clutch'), ('AMT', 'AMT')], max_length=100)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=100)),
                ('year', models.IntegerField()),
                ('total_km_run', models.PositiveIntegerField(help_text='Total distance driven (in km)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mileage', models.FloatField(help_text='Mileage in km/l or km per charge')),
                ('color', models.CharField(max_length=50)),
                ('owner_count', models.IntegerField(default=1, help_text='Number of previous owners')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='car_image')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='app.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_type', to='app.car_type')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Model', to='app.carmodel')),
            ],
        ),
    ]
