# Generated by Django 5.1.4 on 2025-04-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_image1_car_image2_car_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='interior1',
            field=models.ImageField(blank=True, null=True, upload_to='car_interior1'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior2',
            field=models.ImageField(blank=True, null=True, upload_to='car_interior1'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior3',
            field=models.ImageField(blank=True, null=True, upload_to='car_interior1'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior4',
            field=models.ImageField(blank=True, null=True, upload_to='car_interior1'),
        ),
        migrations.AddField(
            model_name='car',
            name='otherimage1',
            field=models.ImageField(blank=True, null=True, upload_to='car_other-img'),
        ),
        migrations.AddField(
            model_name='car',
            name='otherimage2',
            field=models.ImageField(blank=True, null=True, upload_to='car_other-img'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
    ]
