# Generated by Django 5.1.7 on 2025-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_interior1_car_interior2_car_interior3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
