# Generated by Django 5.1.4 on 2025-04-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_car_mileage_car_registraton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='registraton',
            new_name='registration',
        ),
    ]
