# Generated by Django 5.1.7 on 2025-04-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='otherimage1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='otherimage2',
        ),
    ]
